mend/renovate-ce-ee

- docs/configuration.md
Contains a note about shared configs and custom registries.
Thanks for the tip @rarkins ;)
> docs: updated config to include enterprise notes

- examples/docker-compose-ghe.yml
> fix(docs): fix minor docker-compose-ghe.yml typo

- docs/configuration-github.md
This is to resolve the following log statement:
```
WARN: Please set RENOVATE_PLATFORM=github in env
```
> Other: Amend github configuration instructions

- helm-charts/whitesource-renovate/Chart.yaml
This allows Helm to pick up the changes. Otherwise existing installation
won't be updated.
Can you please release/tag a new version after this got merged? :)
> Helm: Increase version and appVersion

- docs/configuration-github.md
This reflects the current UI on github.com
> docs: Update App permissions

- docs/configuration-github.md
> docs: alternate name suggestion

- docs/overview.md
> docs: Add info about /status endpoint

- helm-charts/whitesource-renovate/templates/pvc.yaml
> Fix storageClassName indentation

- docs/README.md
- docs/installation-helm.md
As requested [here](https://github.com/mend/renovate-on-prem/pull/223#discussion_r1012828709).
> docs(install): add some documentation for installation via helm

- artifacthub-repo.yml
> fix: update artifact hub repo config

- helm-charts/whitesource-renovate/Chart.yaml
- helm-charts/whitesource-renovate/README.md
to be shown on artifacthub
#291 should be merged before this
> feat: add a chart readme

- docs/configuration-gitlab.md
So the Dependency Dashboard works through webhooks.
> Add "Issue events"

- README.md
- Some small style changes to the readme file
See above. 🙃
> docs: small style fixes for readme

- docs/installation-helm.md
Corrected the incorrect image path in `installation-helm.md` .
> docs: fix image path

- docs/configure-renovate-ce-github.md
- docs/configure-renovate-ce-gitlab.md
- docs/configure-renovate-ee-github.md
- docs/configure-renovate-ee-gitlab.md
- docs/migrating-to-renovate-ce.md
Fixes #350 
Hello I hope that this changes are in your mind.
From the GitLab documentation I have removed the rate limit on the GitHub app. I think this does not matter with GitLab.
> docs: Improve documentation of what which CronJob does.

- docs/advanced.md
Added `hourly`, `dependency-dashboard`, `rebase-request`, `api-request`
Renamed `master-commit` to `main-commit`
In addition to priority updates
> docs: update job priority mapping

- docs/configure-renovate-ce-github.md
- docs/configure-renovate-ce-gitlab.md
- docs/configure-renovate-ee-github.md
- docs/configure-renovate-ee-gitlab.md
- helm-charts/mend-renovate-ce/Chart.yaml
- helm-charts/mend-renovate-ce/templates/deployment.yaml
- helm-charts/mend-renovate-ce/values.yaml
helm chart + documentation updates for release 6.3.0
New environment variables:
- `MEND_RNV_AUTODISCOVER_FILTER`
- `MEND_RNV_MC_TOKEN`
- `MEND_RNV_GITHUB_PEM_FILE_PATH`
- `MEND_RNV_ENQUEUE_JOBS_ON_STARTUP`
> config: 6.3.0 updates 

- docs/api.md
- docs/configure-renovate-ce-github.md
- docs/configure-renovate-ce-gitlab.md
- docs/configure-renovate-ee-github.md
- docs/configure-renovate-ee-gitlab.md
- helm-charts/mend-renovate-ce/Chart.yaml
- helm-charts/mend-renovate-ce/values.yaml
Sections added
1. log history configuration
2. `/api/status` at the api md
> docs: release 6.4.0

- docs/api.md
- docs/configure-renovate-ce-github.md
- docs/configure-renovate-ce-gitlab.md
- docs/configure-renovate-ee-github.md
- docs/configure-renovate-ee-gitlab.md
- helm-charts/mend-renovate-ce/Chart.yaml
- helm-charts/mend-renovate-ce/values.yaml
Changes:
1. `sqlite3` cli tool mention 
2. `/api/status` section updated
3. Add missing doc entry for `MEND_RNV_SERVER_PORT`
> docs: release 6.5.0

- helm-charts/mend-renovate-ce/Chart.yaml
- helm-charts/mend-renovate-ce/values.yaml
- helm-charts/mend-renovate-ee/Chart.yaml
- helm-charts/mend-renovate-ee/values.yaml
* chore(deps): update dependency renovate to v37.64.2
* feat(docker): add source label and image versions
* fix(github): support suspend/unsuspend webhook event
* fix(logs): improve logging for webhook filtering
* feat: display repo and org counts on startup and in api/status endpoint
> chore: update assets for upcoming release 6.7.0

- helm-charts/mend-renovate-ee/values.yaml
Camel case values for mndRnvPlatform are not accepted
> Update values.yaml to fix typos in comment for mndRnvPlatform

- helm-charts/mend-renovate-ce/templates/deployment.yaml
- helm-charts/mend-renovate-ce/values.yaml
- helm-charts/mend-renovate-ee/templates/deployment-server.yaml
- helm-charts/mend-renovate-ee/values.yaml
allow specifying security context for the container in helm chart, for restricted environments
> feat: container security context

- helm-charts/mend-renovate-ee/templates/deployment-postgresql.yaml
- helm-charts/mend-renovate-ee/templates/deployment-server.yaml
- helm-charts/mend-renovate-ee/templates/deployment-worker.yaml
- helm-charts/mend-renovate-ee/templates/srv-database.yaml
- helm-charts/mend-renovate-ee/templates/srv-server.yaml
- helm-charts/mend-renovate-ee/values.yaml
- logFormat defaults json
- add PostgreSQL support in ee chart
- add replicas for server (not allowed for SQLite)
> Update EE helm chart - add PostgreSQL 

- helm-charts/mend-renovate-ce/templates/deployment.yaml
- helm-charts/mend-renovate-ce/values.yaml
- helm-charts/mend-renovate-ee/templates/deployment-postgresql.yaml
- helm-charts/mend-renovate-ee/templates/deployment-server.yaml
- helm-charts/mend-renovate-ee/templates/deployment-worker.yaml
- helm-charts/mend-renovate-ee/values.yaml
There is a small bug in #420 with the generation of the yaml. I fixed it and did a bit of cleanup.
Would love some feedback.
> fix: Security context indentation bug + cleanup

- helm-charts/mend-renovate-ce/templates/deployment.yaml
- helm-charts/mend-renovate-ce/values.yaml
in my env, i'd like to let renovatebot scan the private AWS ECR repos, i need to attach a service account with IRSA (AWS IAM role for Service Account)
> feat: support service account for the CE deployment

- docs/configure-postgres-db.md
add `MEND_RNV_POSTGRES_SSL_PEM_PATH`
> docs: Update configure-postgres-db.md

- docs/configuration-options.md
- edit description
- add default value
- add notes
> docs: edit MEND_RNV_LOG_HISTORY_DIR description

- docs/configuration-options.md
- docs/configure-renovate-bitbucket-server.md
1. `MEND_RENOVATE_FORKS_PROCESSING`
2. `MEND_RNV_MERGE_CONFIDENCE_ENDPOINT`
3. Bitbucket GA
> docs: release 7.4.0

- helm-charts/mend-renovate-ce/Chart.yaml
- helm-charts/mend-renovate-ce/templates/deployment.yaml
- helm-charts/mend-renovate-ee/Chart.yaml
- helm-charts/mend-renovate-ee/templates/server-deployment.yaml
> Fix readinessProbe

- docs/configuration-options.md
- closes https://github.com/mend/renovate-ce-ee/issues/583#issue-2568756159
> fix(docs): fork processing env typo 
