mend/renovate-ce-ee

docs/configuration-github.md
It looks like the `.npmrc` file should go into `/home/ubuntu/` instead of `/home/node/`.
=> Updated configuration-github to match current home directory

docs/configuration-github.md
One more for you 😄. There are multiple configs now - so it probably makes sense to just link to: `https://github.com/renovatebot/pro/blob/master/examples/`
=> fix(docs): fix dead link to compose examples

docs/configuration-github.md
`Security vulnerability alerts` is known as `Security alerts` in the GitHub Apps creation form.
=> Fix Security alerts label

docs/configuration-github.md
For Github Entreprise you must give read permission to Organization members
The following configuration in `renovate.json` to work on GHE on perm
```json
{
"reviewers": [
"team:my-team"
],
}
```
Otherwise the following error occurs:
```json
"err": {
"message": "platform-failure",
"stack": "Error: platform-failure\n    at get (/usr/src/app/node_modules/renovate/dist/platform/github/gh-got-wrapper.js:131:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
}
```
I had to hack `gh-got-wrapper.js` on the docker image renovate/pro:0.18.5 with a  `logger_1.logger.info({ err }, "WTF renovate")` in order to find the error from github
```json
{
// ...
"body": {
"message": "Validation Failed",
"errors": [
"Could not resolve to a node with the global id of 'MDQ6VGVhbTEwMQ=='."
], …
```
=> docs: assigning team reviewers requires organization read access

helm-charts/whitesource-renovate/templates/deployment.yaml, helm-charts/whitesource-renovate/values.yaml
This allows to inject extra environment variables for the helm chart deployment.
=> Add extraEnvVars to the helm chart deployment

helm-charts/whitesource-renovate/templates/service.yaml, helm-charts/whitesource-renovate/values.yaml
In a mixed environment it is sometimes necessary to route traffic from Services inside the same (virtual) network address block.
It is useful to be able to set the service to annotations in that case.
=> Support for annotations in service

README.md
GitHub redirects to main since the master branch is not the default branch for **whitesource/renovate-on-prem**.
=> fix(doc): update ref on the link

docs/advanced.md
- `GiHub` -> `GitHub`
Fixing a typo.
=> docs: fix typo

docs/configuration-gitlab.md
- `team mate's account` -> `teammate's account`
Teammate is one word.
=> docs: fix grammar

helm-charts/whitesource-renovate/templates/deployment.yaml, helm-charts/whitesource-renovate/values.yaml
We ran into the use case where we're using Vault CSI and secrets won't get created without a volume to initiate the process. So submitting this PR to add the ability to add extra volumes as necessary.
=> feat: add extra volume and volumemount to helm template

helm-charts/whitesource-renovate/templates/_helpers.tpl, helm-charts/whitesource-renovate/templates/deployment.yaml, helm-charts/whitesource-renovate/templates/secret.yaml, helm-charts/whitesource-renovate/values.yaml
Piggybacking off of https://github.com/whitesource/renovate-on-prem/pull/156, these are the changes that we're using. Had issues with original PR not passing helm linting and also having rendering issues with newlines. This PR appropriately renders now for `values.yaml` with and without existing secrets (both general and npmrc). 
Also added better documentation in the `values.yaml` for the existing secrets' expected keys for better UX.
=> feat: add existingSecret in helm template

helm-charts/whitesource-renovate/templates/deployment.yaml, helm-charts/whitesource-renovate/templates/pvc.yaml, helm-charts/whitesource-renovate/values.yaml
This allows the cache dir to be moved to an PVC. This makes it possible to keep the cache on pod recreation.
=> Allow cache directory to be moved to PVC

helm-charts/whitesource-renovate/Chart.yaml, helm-charts/whitesource-renovate/templates/deployment.yaml
Add pod annotations to the helm chart. Our use case was adding kube2iam annotations for AWS IAM roles.
=> feat: add pod annotations to helm chart

helm-charts/whitesource-renovate/Chart.yaml, helm-charts/whitesource-renovate/templates/configmap.yaml, helm-charts/whitesource-renovate/templates/deployment.yaml, helm-charts/whitesource-renovate/templates/ingress.yaml, helm-charts/whitesource-renovate/templates/pvc.yaml, helm-charts/whitesource-renovate/templates/secret.yaml, helm-charts/whitesource-renovate/templates/service.yaml
When deploying with something like Spinnaker, there's no standard namespace assigned in the chart which can lead to default namespace deployment when not using something like `helm3` to generate. This adds the standard built-in object `.Release.Namespace` which inherits the namespace when passed in via helm CLI. So this will be a no-op for helm users, and this will appropriately source the value for third party manifest baking (like Spinnaker). 
This also bumps the helm chart version, and pins the correct app version (since we're now on 2.5.1 instead of 2.1.1)
=> helm-chart: add .Release.Namespace to chart templates

docs/configuration-gitlab.md
According to my personal testing as well as the documentation in the renovate_runner project on gitlab indicates that the `write_repository` permission is required not just "read".
=> Correction of required permissions for gitlab bot user

helm-charts/whitesource-renovate/Chart.yaml, helm-charts/whitesource-renovate/templates/deployment.yaml, helm-charts/whitesource-renovate/values.yaml
I've noticed that the Renovate pod gets restarted quite often due to the liveness probe failing, even though the logs seem to indicate Renovate is running properly. This PR makes it possible to configure the liveness and readiness probes for the container for end users. The default values are the same as the ones configured in the deployment, although a bit more verbose to show users which values can be changed.
=> make liveness and readiness probes configurable

README.md, docs/advanced.md, docs/configuration-github.md, docs/configuration-gitlab.md, docs/installation-helm.md, helm-charts/whitesource-renovate/README.md
- Use one sentence per line pattern for documentation files
- Add a missing full stop to the end of a sentence
- Remove the `>` quote layout in two files
Closes #272
=> docs: one sentence per line

helm-charts/whitesource-renovate/Chart.yaml, helm-charts/whitesource-renovate/templates/deployment.yaml
This PR makes configuration values that are not required on all platforms/for all configurations optional.
This is required when using the `existingSecret` to not require values to be set when they are not used.
Resolves #298.
=> fix: make optional configuration values optional

.github/ct.yaml, .github/workflows/lint.yml, helm-charts/whitesource-renovate/Chart.yaml, helm-charts/whitesource-renovate/templates/deployment.yaml, helm-charts/whitesource-renovate/values.yaml, renovate.json
This contains the following:
- Make `terminationGracePeriodSeconds` configurable
- Improve templating by not including `securityContext` if empty
- Migrate renovate config
- Add helm lint workflow to ensure syntactic correctness of chart
=> feat: make terminationGracePeriodSeconds configurable

docs/configuration-gitlab.md
The GitLab docs ask you to set `MEND_RNV_PLATFORM` to `github` which is obviously wrong.
=> docs: fix gitlab platform

docs/migrating-to-renovate-ce.md
It seems that `PORT` has been renamed to `MEND_RNV_SERVER_PORT`. Documenting this would help users who are migrating to Renovate CE without using the provided Helm chart.
=> Document PORT env var change

helm-charts/mend-renovate-ce/Chart.yaml, helm-charts/mend-renovate-ce/values.yaml
With this change, the SQLite database is persisted by default when cachePersistence is turned on.
Part of #357.
=> fix: persist SQLite database by default

docs/configure-renovate-ce-github.md, docs/configure-renovate-ce-gitlab.md, docs/configure-renovate-ee-github.md, docs/configure-renovate-ee-gitlab.md, helm-charts/mend-renovate-ce/Chart.yaml, helm-charts/mend-renovate-ce/values.yaml, helm-charts/mend-renovate-ee/Chart.yaml, helm-charts/mend-renovate-ee/values.yaml
- feat(github): Verify GitHub App permissions during Sync
- feat: Add worker health endpoint
- fix: Add docker labels
- fix(worker): Execution timeout, introduce MEND_RNV_WORKER_EXECUTION_TIMEOUT
- fix(worker): Use the Dockerfile-bundled Node runtime to run the Renovate CLI
- fix: Terminate the entire GPID when timing out a scan
- fix: Apply worker config at the worker source
- fix(docker): Add labels to ee-server
=> docs: release 6.6.0

docs/configure-renovate-ee-github.md, docs/configure-renovate-ee-gitlab.md
It is not clear to me from the doc where the config should be, but it seems like this is the correct place. Please edit or discard this PR if this is wrong, but I think the wording around the config should be improved to reflect where this should be done.
=> docs: clarify Renovate OSS config location in EE

docs/configure-renovate-ee-gitlab.md
- Modify MEND_RNV_ENDPOINT to GitLab example.
- In docker-compose.yml. Since it is a GitLab example, MEND_RNV_GITLAB_PAT should be added, and GitHub-related parameters should be commented out.
=> Docs for Renovate EE gitlab

helm-charts/mend-renovate-ce/values.yaml, helm-charts/mend-renovate-ee/values.yaml
Tests showed, that Renovate is nowadays basically instantly available:
```
$ kubectl logs renovate-ce-mend-renovate-ce-54c6876b54-n67qb | head -n 1
{"name":"renovate","hostname":"renovate-ce-mend-renovate-ce-54c6876b54-n67qb","pid":8,"level":30,"logContext":"u_lAjxMgmbLNtLiWuOnCD","input":"y","msg":"Validating terms of service agreement","time":"2024-03-20T13:15:17.494Z","v":0}
$ kubectl logs renovate-ce-mend-renovate-ce-54c6876b54-n67qb | grep 'Server listening on port 8080'
{"name":"renovate","hostname":"renovate-ce-mend-renovate-ce-54c6876b54-n67qb","pid":8,"level":30,"logContext":"u_lAjxMgmbLNtLiWuOnCD","alias":"renovate-server","msg":"Server listening on port 8080","time":"2024-03-20T13:15:23.555Z","v":0}
```
=> Reduce the initialDelaySeconds to 2s

docs/configuration-options.md, helm-charts/mend-renovate-ce/Chart.yaml, helm-charts/mend-renovate-ce/templates/deployment.yaml, helm-charts/mend-renovate-ce/values.yaml, helm-charts/mend-renovate-ee/Chart.yaml, helm-charts/mend-renovate-ee/templates/server-deployment.yaml, helm-charts/mend-renovate-ee/templates/worker-deployment.yaml, helm-charts/mend-renovate-ee/values.yaml
bump charts version to: `7.0.0`
bump charts appVersion: `7.0.0`
Community:
- `MEND_RNV_SYNC_ON_STARTUP`
- `MEND_RNV_SYNC_MODE`
- `MEND_RNV_REPORTING_ENABLED` 
- `MEND_RNV_LOG_HISTORY_S3`
- `MEND_RNV_WORKER_CLEANUP`
- `RENOVATE_NODE_ARGS`
- `MEND_RNV_WORKER_CLEANUP_DIRS`
Enterprise:
- `MEND_RNV_SYNC_ON_STARTUP`
- `MEND_RNV_SYNC_MODE`
- `MEND_RNV_MC_TOKEN`
- `MEND_RNV_REPORTING_ENABLED`
- `MEND_RNV_LOG_HISTORY_S3`
- `MEND_RNV_WORKER_CLEANUP`
- `RENOVATE_NODE_ARGS`
- `MEND_RNV_WORKER_CLEANUP_DIRS`
- fix bug in server deployment replace `renovate.existingSecret` with `renovateServer.existingSecret`
=> V7 charts update

helm-charts/mend-renovate-ce/templates/_helpers.tpl, helm-charts/mend-renovate-ce/templates/deployment.yaml, helm-charts/mend-renovate-ce/templates/serviceaccount.yaml, helm-charts/mend-renovate-ce/values.yaml, helm-charts/mend-renovate-ee/templates/_helpers.tpl, helm-charts/mend-renovate-ee/templates/server-deployment.yaml, helm-charts/mend-renovate-ee/templates/server-serviceaccount.yaml, helm-charts/mend-renovate-ee/templates/worker-deployment.yaml, helm-charts/mend-renovate-ee/templates/worker-serviceaccount.yaml, helm-charts/mend-renovate-ee/values.yaml
This change allows Renovate pods to be assigned roles with IAM permissions, enabling access to things like private AWS ECR repositories.
The update in CE is designed to be backward compatible with the existing functionality, but using `.serviceAccount.existingName` should be preferred as its more clear when the Helm chart is managing creation of the SA. The update to EE does not include the form from CE, as this is net new functionality for the EE chart.
=> feat: allow creating or using service accounts

helm-charts/mend-renovate-ee/templates/worker-deployment.yaml
Adds an appropriate label to the worker deployment. Without this, the worker deployment selector also matches the server deployment pods.
=> fix: add appropriate selector and label for worker pods

helm-charts/mend-renovate-ce/templates/deployment.yaml, helm-charts/mend-renovate-ee/templates/worker-deployment.yaml
When the `config` value is changed, it causes the config map to be updated, but this does not cause worker nodes to automatically pick up this new configuration. By adding an annotation based on the checksum of that generated config map, the pod spec will change when the config map changes. This will cause worker pods to automatically restart to pick up the updated configuration values.
=> fix: add annotation that will restart worker pods on config update

docs/configure-renovate-ce-github.md
I reordered permissions in documentation to better map Github's layout to increase UX.
=> docs: reorder permissions in configure-renovate-ce-github.md

helm-charts/mend-renovate-ce/templates/deployment.yaml, helm-charts/mend-renovate-ce/values.yaml, helm-charts/mend-renovate-ee/templates/server-deployment.yaml, helm-charts/mend-renovate-ee/values.yaml
The code changes add the `mendRnvGithubBotUserId` configuration option to the `values.yaml` file. This option allows specifying the GitHub bot user ID for the Mend Renovate app which can be found by calling `https://api.github.com/users/{appName}[bot]` under the `id` key (replace the `{appName}` with the actual app name).
=> feat: Add `mendRnvGithubBotUserId` configuration option

helm-charts/mend-renovate-ce/templates/serviceaccount.yaml, helm-charts/mend-renovate-ee/templates/server-serviceaccount.yaml, helm-charts/mend-renovate-ee/templates/worker-serviceaccount.yaml
Now, I want to use my a kubernetes service account in helm chart, I want to use SA to grant some permission for AWS ECR, and then the renovate will start failed due to the deployment depends on a not existing SA.
My values yaml is:
```yaml
...
serviceAccount:
create: true
...
```
The service account name in deployment is: `mend-renovate-ce-sa`, but  its in service account is: `renovate-mend-renovate-ce-sa`.
=> feat: Using service account variable in SA yaml file

helm-charts/mend-renovate-ce/Chart.yaml, helm-charts/mend-renovate-ce/templates/deployment.yaml, helm-charts/mend-renovate-ce/values.yaml, helm-charts/mend-renovate-ee/Chart.yaml, helm-charts/mend-renovate-ee/templates/server-deployment.yaml, helm-charts/mend-renovate-ee/values.yaml
CE chart:
* bump images to 8.0.0
* replace `MEND_RNV_CRON_JOB_SCHEDULER` with `MEND_RNV_CRON_JOB_SCHEDULER_ALL`
* add `MEND_RENOVATE_FORKS_PROCESSING`
EE chart: 
* bump images to 8.0.0
* replace `MEND_RNV_CRON_JOB_SCHEDULER` with `MEND_RNV_CRON_JOB_SCHEDULER_HOT`
* add `MEND_RNV_CRON_JOB_SCHEDULER_COLD`
* add `MEND_RNV_CRON_JOB_SCHEDULER_CAPPED`
* add `MEND_RNV_CRON_JOB_SCHEDULER_ALL`
* add `MEND_RENOVATE_FORKS_PROCESSING`
* add `MEND_RNV_MERGE_CONFIDENCE_ENDPOINT`
=> feat: bump ce chart to 8.0.0

docs/configuration-options.md, docs/configure-renovate-bitbucket-server.md, docs/configure-renovate-ce-github.md, docs/configure-renovate-ce-gitlab.md, examples/docker-compose/renovate-ce-github.yml, examples/docker-compose/renovate-ce-postgres.yml, examples/env/mend-renovate.env, helm-charts/mend-renovate-ce/values.yaml
Provided information about the 10-repo license key.
Updated configuration options plus examples (docker and helm)
=> docs: added the 10-repo license key for Community Edition

helm-charts/mend-renovate-ce/templates/deployment.yaml, helm-charts/mend-renovate-ce/values.yaml, helm-charts/mend-renovate-ee/templates/server-deployment.yaml, helm-charts/mend-renovate-ee/templates/worker-deployment.yaml, helm-charts/mend-renovate-ee/values.yaml
CE:
* MEND_RNV_DISABLE_GLOBAL_AGENT
* MEND_RNV_ENABLE_HTTP2
EE server:
* MEND_RNV_DISABLE_GLOBAL_AGENT
* MEND_RNV_ENABLE_HTTP2
EE worker:
* MEND_RNV_DISABLE_GLOBAL_AGENT
* MEND_RNV_ENABLE_HTTP2
=> feat: add enbale http2 and disable globalAgent to charts
